# https://docs.travis-ci.com/
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
# command to run tests
script:
#  - py.test
  - echo "online test disabled"
#after_success:
#  - coveralls
notifications:
    webhooks:
      - https://jianliao.com/v2/services/webhook/3e1779ce20f15f1337b107784b043751728ed9e1
    slack:
      on_success: never
      on_failure: never
