language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
# command to run tests
script:
  - coverage run setup.py test
after_success:
  - coveralls
notifications:
    webhooks:
      - https://hook.lesschat.com/travisci/0a425481371c405990a7ffc73ae4b299
