language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
# command to run tests
script:
  - python setup.py test
after_success:
  - coveralls
notifications:
    webhooks:
      - https://hook.lesschat.com/travisci/0a425481371c405990a7ffc73ae4b299
    slack:
      on_success: never
      on_failure: never
